<a href="https://colab.research.google.com/github/LookUpJosh/DeepLearningPytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# A torch. Tensor is a multi-dimensional matrix containing  delements of a single
# data type. Similar to numpy arrys, but full of fun things that make them work
# better with GPUs
# default data type = float32
# more suitable for deep learning than a numpy array

import torch
import numpy as np

In [3]:
# Lists
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.2565067 , 0.79431696, 0.26629981, 0.08761525],
       [0.22924518, 0.42190634, 0.60345045, 0.22161427],
       [0.00300035, 0.78825511, 0.32767071, 0.7137478 ]])

In [7]:
np1.dtype

dtype('float64')

In [9]:
# tensor
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.2596, -0.9074,  0.9507,  0.0265],
        [-0.3253, -0.6489, -1.1607, -0.4889],
        [-0.4491, -0.4268, -0.7353, -0.6019]])

In [10]:
tensor_3d = torch .zeros(3,4,5)
tensor_3d


tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [11]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2565, 0.7943, 0.2663, 0.0876],
        [0.2292, 0.4219, 0.6035, 0.2216],
        [0.0030, 0.7883, 0.3277, 0.7137]], dtype=torch.float64)